server:
  port: 8090
spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: 192.168.0.120:2181
    config:
      server:
        git:
          uri: https://github.com/hexinquan/spring-cloud-configs
          username: 630050024@qq.com
          password: hxq98543697
  application:
    name: config-center
